classes:
- system.linux.system.sudo
- system.openssh.server.team.members.deprecated.miwinski
- system.openssh.server.team.members.deprecated.mniedbala
- system.openssh.server.team.members.deprecated.pcizinsky
- system.openssh.server.team.members.deprecated.pmichalec
- system.openssh.server.team.members.deprecated.sflorczak
- system.openssh.server.team.members.deprecated.vblokhin
- system.openssh.server.team.members.alis
- system.openssh.server.team.members.alugovoi
- system.openssh.server.team.members.dbogaczyk
- system.openssh.server.team.members.dkruglov
- system.openssh.server.team.members.dnikishov
- system.openssh.server.team.members.dstremkouski
- system.openssh.server.team.members.hkraemer
- system.openssh.server.team.members.isviridov
- system.openssh.server.team.members.jwasilewski
- system.openssh.server.team.members.korlowska
- system.openssh.server.team.members.lmercl
- system.openssh.server.team.members.mchernik
- system.openssh.server.team.members.osavatieiev
- system.openssh.server.team.members.oaleksieiev
- system.openssh.server.team.members.pbasov
- system.openssh.server.team.members.pruzicka
- system.openssh.server.team.members.pvaylov
- system.openssh.server.team.members.sburns
- system.openssh.server.team.members.srogov
- system.openssh.server.team.members.vkuspits
- system.openssh.server.team.members.yisakov
- system.openssh.server.team.members.qwu
- system.openssh.server.team.members.srudyka
- system.openssh.server.team.members.kambrozy
- system.openssh.server.team.members.calexiu
parameters:
  _param:
    linux_system_user_sudo: true
